# Generated by Django 3.2.16 on 2023-01-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=25)),
                ('item_name', models.CharField(max_length=200)),
                ('item_uom', models.CharField(max_length=50)),
                ('item_barcode', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=50)),
                ('item_kitchen', models.CharField(max_length=50)),
                ('item_production_cost', models.FloatField(max_length=10)),
                ('item_sales_rate', models.FloatField(max_length=10)),
                ('item_branch_sales_rate', models.FloatField(max_length=10)),
                ('item_mrp', models.FloatField(max_length=10)),
                ('item_image', models.ImageField(upload_to='itemimages')),
                ('flag', models.IntegerField()),
            ],
        ),
    ]
