# Generated by Django 3.2.16 on 2023-01-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230119_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=200)),
                ('branch_description', models.CharField(max_length=250)),
                ('branch_created_by', models.CharField(max_length=200)),
                ('branch_flag', models.IntegerField()),
            ],
        ),
    ]
