# Generated by Django 3.2.16 on 2023-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_branch_1_branch_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='consolidated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=25)),
                ('item_name', models.CharField(max_length=200)),
                ('item_uom', models.CharField(max_length=50)),
                ('item_barcode', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=50)),
                ('item_kitchen', models.CharField(max_length=50)),
                ('item_production_cost', models.FloatField(max_length=10)),
                ('item_sales_rate', models.FloatField(max_length=10)),
                ('item_branch_sales_rate', models.FloatField(max_length=10)),
                ('item_mrp', models.FloatField(max_length=10)),
                ('item_image', models.ImageField(upload_to='itemimages')),
                ('item_description', models.CharField(max_length=250)),
                ('item_created_by', models.CharField(max_length=200)),
                ('order_qty_br1', models.FloatField()),
                ('order_qty_br1_date', models.DateTimeField()),
                ('order_qty_br2', models.FloatField()),
                ('order_qty_br2_date', models.DateTimeField()),
                ('order_qty_br3', models.FloatField()),
                ('order_qty_br3_date', models.DateTimeField()),
                ('item_flag', models.IntegerField()),
            ],
        ),
    ]
