# Generated by Django 3.2.16 on 2023-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_consolidated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidated',
            name='order_qty_br1_date',
            field=models.DateField(),
        ),
    ]
