# Generated by Django 3.2.16 on 2023-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_consolidated_order_qty_br1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidated',
            name='order_qty_br2_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consolidated',
            name='order_qty_br3_date',
            field=models.DateField(),
        ),
    ]
