# Generated by Django 3.2.16 on 2023-01-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_branch_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
