# Generated by Django 3.2.16 on 2023-01-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20230125_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
