# Generated by Django 3.2.16 on 2023-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_flage',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
