# Generated by Django 3.2.16 on 2023-01-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_user_flage'),
    ]

    operations = [
        migrations.CreateModel(
            name='catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergory_name', models.CharField(max_length=200)),
                ('catergory_created_by', models.CharField(max_length=200)),
                ('catergory_flag', models.CharField(max_length=2)),
            ],
        ),
    ]
